"""Static shell completion for the msmodeling CLI entry points.

The rendered completion is pure shell code so pressing Tab never starts Python
or imports heavyweight runtime dependencies. The default bash/zsh path is
deliberately shell-local:

    . <(msmodeling-tab)

For PowerShell:

    msmodeling-tab --shell powershell | iex

That one-liner sources the generated script into the current shell without
editing ``~/.bashrc``, ``~/.zshrc``, or any other user shell startup file.
"""

from __future__ import annotations

import argparse
import os
import shutil
import site
from pathlib import Path
import sys


MODULES = (
    "cli.inference.text_generate",
    "cli.inference.video_generate",
    "cli.inference.throughput_optimizer",
)

COMMON_OPTIONS = (
    "--device",
    "--num-devices",
    "--reserved-memory-gb",
    "--log-level",
)

OPTIONS = {
    "text_generate": (
        *COMMON_OPTIONS,
        "--num-queries",
        "--query-length",
        "--context-length",
        "--decode",
        "--prefix-cache-hit-rate",
        "--num-mtp-tokens",
        "--disable-repetition",
        "--compile",
        "--compile-allow-graph-break",
        "--quantize-linear-action",
        "--quantize-lmhead",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--graph-log-url",
        "--dump-input-shapes",
        "--chrome-trace",
        "--num-hidden-layers-override",
        "--tp-size",
        "--dp-size",
        "--ep-size",
        "--o-proj-tp-size",
        "--o-proj-dp-size",
        "--mlp-tp-size",
        "--mlp-dp-size",
        "--lmhead-tp-size",
        "--lmhead-dp-size",
        "--moe-tp-size",
        "--moe-dp-size",
        "--word-embedding-tp",
        "--enable-redundant-experts",
        "--enable-external-shared-experts",
        "--host-external-shared-experts",
        "--image-batch-size",
        "--image-height",
        "--image-width",
        "--remote-source",
        "--performance-model",
        "--profiling-database",
        "--help",
    ),
    "video_generate": (
        "--device",
        "--batch-size",
        "--seq-len",
        "--chrome-trace",
        "--height",
        "--width",
        "--frame-num",
        "--sample-step",
        "--log-level",
        "--dtype",
        "--quantize-linear-action",
        "--use-cfg",
        "--world-size",
        "--ulysses-size",
        "--cfg-parallel",
        "--dit-cache",
        "--cache-step-range",
        "--cache-step-interval",
        "--cache-block-range",
        "--help",
    ),
    "throughput_optimizer": (
        *COMMON_OPTIONS,
        "--input-length",
        "--output-length",
        "--compile",
        "--compile-allow-graph-break",
        "--num-mtp-tokens",
        "--mtp-acceptance-rate",
        "--prefix-cache-hit-rate",
        "--quantize-linear-action",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--tp-sizes",
        "--ep-sizes",
        "--moe-dp-sizes",
        "--ttft-limits",
        "--tpot-limits",
        "--max-prefill-tokens",
        "--batch-range",
        "--serving-cost",
        "--disagg",
        "--jobs",
        "--dump-original-results",
        "--image-height",
        "--image-width",
        "--prefill-devices-per-instance",
        "--decode-devices-per-instance",
        "--enable-optimize-prefill-decode-ratio",
        "--help",
    ),
    "serving_cast_main": (
        "--instance_config_path",
        "--common_config_path",
        "--enable_profiling",
        "--profiling_output_path",
        "--help",
    ),
}

LEGACY_BLOCK_BEGIN = "# >>> msmodeling completion >>>"
LEGACY_BLOCK_END = "# <<< msmodeling completion <<<"
LEGACY_HOME_DIR = Path.home() / ".local" / "share" / "msmodeling"


def _words(values: tuple[str, ...]) -> str:
    return " ".join(values)


def _ps_array(values: tuple[str, ...]) -> str:
    return "@(" + ", ".join(f"'{value}'" for value in values) + ")"


def render_bash_completion() -> str:
    """Return a self-contained bash completion script."""
    return f"""# Static completion for msmodeling.
# Generated by msmodeling-tab. Re-run after CLI option changes.

_msmodeling_complete()
{{
    local cur target
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"

    if [[ $COMP_CWORD -gt 0 && ${{COMP_WORDS[COMP_CWORD - 1]}} == "-m" ]]; then
        COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
        return 0
    fi

    case "$cur" in
        cli.inference.*)
            COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
            return 0
            ;;
    esac

    target="$(_msmodeling_completion_target)"
    if [[ -z "$target" || "$cur" != --* ]]; then
        return 0
    fi

    case "$target" in
        text_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["text_generate"])}" -- "$cur") )
            ;;
        video_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["video_generate"])}" -- "$cur") )
            ;;
        throughput_optimizer)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["throughput_optimizer"])}" -- "$cur") )
            ;;
        serving_cast_main)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["serving_cast_main"])}" -- "$cur") )
            ;;
    esac
}}

_msmodeling_completion_target()
{{
    local i word next
    for ((i = 1; i < COMP_CWORD; i++)); do
        word="${{COMP_WORDS[i]}}"
        next="${{COMP_WORDS[i + 1]}}"

        if [[ "$word" == "-m" ]]; then
            case "$next" in
                cli.inference.text_generate) echo text_generate; return 0 ;;
                cli.inference.video_generate) echo video_generate; return 0 ;;
                cli.inference.throughput_optimizer) echo throughput_optimizer; return 0 ;;
                serving_cast.main) echo serving_cast_main; return 0 ;;
            esac
        fi

        case "$word" in
            */cli/inference/text_generate.py|cli/inference/text_generate.py|text_generate.py)
                echo text_generate; return 0 ;;
            */cli/inference/video_generate.py|cli/inference/video_generate.py|video_generate.py)
                echo video_generate; return 0 ;;
            */cli/inference/throughput_optimizer.py|cli/inference/throughput_optimizer.py|throughput_optimizer.py)
                echo throughput_optimizer; return 0 ;;
            */serving_cast/main.py|serving_cast/main.py)
                echo serving_cast_main; return 0 ;;
        esac
    done
}}

complete -o default -F _msmodeling_complete python python3
"""


def render_zsh_completion() -> str:
    """Return a self-contained zsh completion script via bashcompinit."""
    return (
        "# Static completion for msmodeling in zsh via bashcompinit.\n"
        "autoload -Uz +X compinit && compinit -u 2>/dev/null\n"
        "autoload -Uz +X bashcompinit && bashcompinit\n"
        + render_bash_completion()
    )


def render_powershell_completion() -> str:
    """Return a self-contained PowerShell completion script."""
    return f"""# Static completion for msmodeling.
# Generated by msmodeling-tab. Re-run after CLI option changes.

$script:MsmodelingModules = {_ps_array(MODULES)}
$script:MsmodelingOptions = @{{
    'text_generate' = {_ps_array(OPTIONS["text_generate"])}
    'video_generate' = {_ps_array(OPTIONS["video_generate"])}
    'throughput_optimizer' = {_ps_array(OPTIONS["throughput_optimizer"])}
    'serving_cast_main' = {_ps_array(OPTIONS["serving_cast_main"])}
}}

function Get-MsmodelingCompletionTarget {{
    param([string[]] $Words)

    for ($i = 1; $i -lt $Words.Count; $i++) {{
        $word = $Words[$i]
        $next = if ($i + 1 -lt $Words.Count) {{ $Words[$i + 1] }} else {{ "" }}

        if ($word -eq "-m") {{
            switch ($next) {{
                "cli.inference.text_generate" {{ return "text_generate" }}
                "cli.inference.video_generate" {{ return "video_generate" }}
                "cli.inference.throughput_optimizer" {{ return "throughput_optimizer" }}
                "serving_cast.main" {{ return "serving_cast_main" }}
            }}
        }}

        switch -Wildcard ($word) {{
            "*/cli/inference/text_generate.py" {{ return "text_generate" }}
            "*\\cli\\inference\\text_generate.py" {{ return "text_generate" }}
            "cli/inference/text_generate.py" {{ return "text_generate" }}
            "cli\\inference\\text_generate.py" {{ return "text_generate" }}
            "text_generate.py" {{ return "text_generate" }}
            "*/cli/inference/video_generate.py" {{ return "video_generate" }}
            "*\\cli\\inference\\video_generate.py" {{ return "video_generate" }}
            "cli/inference/video_generate.py" {{ return "video_generate" }}
            "cli\\inference\\video_generate.py" {{ return "video_generate" }}
            "video_generate.py" {{ return "video_generate" }}
            "*/cli/inference/throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "*\\cli\\inference\\throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "cli/inference/throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "cli\\inference\\throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "*/serving_cast/main.py" {{ return "serving_cast_main" }}
            "*\\serving_cast\\main.py" {{ return "serving_cast_main" }}
            "serving_cast/main.py" {{ return "serving_cast_main" }}
            "serving_cast\\main.py" {{ return "serving_cast_main" }}
        }}
    }}
}}

Register-ArgumentCompleter -Native -CommandName @("python", "python3") -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = @($commandAst.CommandElements | ForEach-Object {{ $_.ToString() }})
    if ($words.Count -gt 1 -and $words[$words.Count - 2] -eq "-m") {{
        $script:MsmodelingModules |
            Where-Object {{ $_ -like "$wordToComplete*" }} |
            ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_) }}
        return
    }}

    if ($wordToComplete -like "cli.inference.*") {{
        $script:MsmodelingModules |
            Where-Object {{ $_ -like "$wordToComplete*" }} |
            ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_) }}
        return
    }}

    $target = Get-MsmodelingCompletionTarget -Words $words
    if (-not $target -or -not $wordToComplete.StartsWith("--")) {{
        return
    }}

    $script:MsmodelingOptions[$target] |
        Where-Object {{ $_ -like "$wordToComplete*" }} |
        ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterName", $_) }}
}}
"""


def _detect_shell() -> str:
    try:
        comm = Path(f"/proc/{os.getppid()}/comm").read_text(encoding="utf-8").strip()
        if comm in {"bash", "zsh"}:
            return comm
        if comm in {"pwsh", "powershell"}:
            return "powershell"
    except OSError:
        pass

    shell_path = Path(os.environ.get("SHELL", ""))
    shell_name = shell_path.name.lower() if shell_path.name else ""

    # Git Bash / MSYS2 / Cygwin still run on Windows, but `$SHELL` points at bash/zsh.
    if shell_name in {"bash", "zsh"}:
        return shell_name

    powershell_signals = ("PSModulePath", "POWERSHELL_DISTRIBUTION_CHANNEL")

    msys_signals = ("MSYSTEM", "MINGW_PREFIX", "CHERE_INVOKING")

    # Prefer bash/zsh on MSYS/Git Bash shells even inside Windows Terminal.
    if (
        shell_name != "bash"
        and os.name == "nt"
        and not any(os.environ.get(k) for k in msys_signals)
        and any(os.environ.get(k) for k in powershell_signals)
    ):
        return "powershell"

    if os.environ.get("PSModulePath"):
        return "powershell"

    # Last resort fallback.
    return "bash"


def _resolve_shell(value: str) -> str:
    if value in {"bash", "zsh", "powershell"}:
        return value
    return _detect_shell()


def _default_prefix(user: bool) -> Path:
    """Return the install prefix for optional on-disk completion files."""
    if user:
        return Path(site.getuserbase())
    return Path(sys.prefix)


def _bash_target(prefix: Path) -> Path:
    return prefix / "share" / "bash-completion" / "completions" / "msmodeling-python"


def _zsh_target(prefix: Path) -> Path:
    return prefix / "share" / "zsh" / "site-functions" / "_msmodeling-python"


def _powershell_target(prefix: Path) -> Path:
    return prefix / "share" / "powershell" / "Completions" / "msmodeling.ps1"


def _write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def _install(args: argparse.Namespace) -> int:
    prefix = Path(args.prefix) if args.prefix else _default_prefix(args.user)
    bash_path = _bash_target(prefix)
    zsh_path = _zsh_target(prefix)
    powershell_path = _powershell_target(prefix)
    _write(bash_path, render_bash_completion())
    _write(zsh_path, render_zsh_completion())
    _write(powershell_path, render_powershell_completion())
    print(f"Wrote bash completion: {bash_path}")
    print(f"Wrote zsh  completion: {zsh_path}")
    print(f"Wrote PowerShell completion: {powershell_path}")
    print()
    print("These files live entirely under the install prefix.")
    print("No shell startup file under $HOME was modified.")
    print()
    print("To activate completion in the current shell without touching $HOME:")
    print("  bash/zsh:    . <(msmodeling-tab)")
    print("  PowerShell:  msmodeling-tab --shell powershell | iex")
    print("  (or)         python -m cli.completion --shell powershell | iex")
    return 0


def _print(args: argparse.Namespace) -> int:
    shell = _resolve_shell(args.shell)
    if shell == "zsh":
        sys.stdout.write(render_zsh_completion())
    elif shell == "powershell":
        sys.stdout.write(render_powershell_completion())
    else:
        sys.stdout.write(render_bash_completion())
    return 0


def _cleanup_legacy(args: argparse.Namespace) -> int:
    """Remove files written by the old rc-editing install path."""
    changed = False

    for rc_file in (Path.home() / ".bashrc", Path.home() / ".zshrc"):
        if not rc_file.is_file():
            continue
        original = rc_file.read_text(encoding="utf-8")
        if LEGACY_BLOCK_BEGIN not in original:
            continue

        cleaned_lines: list[str] = []
        skip = False
        for line in original.splitlines(keepends=True):
            stripped = line.strip()
            if stripped == LEGACY_BLOCK_BEGIN:
                skip = True
                continue
            if stripped == LEGACY_BLOCK_END:
                skip = False
                continue
            if not skip:
                cleaned_lines.append(line)

        if args.dry_run:
            print(f"[dry-run] would remove legacy completion block from {rc_file}")
        else:
            rc_file.write_text("".join(cleaned_lines), encoding="utf-8")
            print(f"Removed legacy completion block from {rc_file}")
            changed = True

    if LEGACY_HOME_DIR.exists():
        if args.dry_run:
            print(f"[dry-run] would remove legacy data dir {LEGACY_HOME_DIR}")
        else:
            shutil.rmtree(LEGACY_HOME_DIR, ignore_errors=True)
            print(f"Removed legacy data dir {LEGACY_HOME_DIR}")
            changed = True

    if not changed and not args.dry_run:
        print("Nothing to clean up.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Emit or install static shell completion for msmodeling CLI entry "
            "points. Default behavior never modifies $HOME."
        ),
    )
    parser.add_argument(
        "--shell",
        choices=("auto", "bash", "zsh", "powershell"),
        default="auto",
        help="target shell for default output; auto detects the current shell",
    )
    subparsers = parser.add_subparsers(dest="command")

    install_parser = subparsers.add_parser(
        "install",
        help="write completion files under <prefix>/share without touching shell rc files",
    )
    install_parser.add_argument(
        "--prefix",
        default=None,
        help="install prefix; defaults to sys.prefix or site.getuserbase() with --user",
    )
    install_parser.add_argument(
        "--user",
        action="store_true",
        help="use the Python user base as the install prefix",
    )
    install_parser.set_defaults(func=_install)

    print_parser = subparsers.add_parser("print", help="print completion script")
    print_parser.add_argument(
        "--shell",
        choices=("auto", "bash", "zsh", "powershell"),
        default="auto",
        help="target shell; auto detects the parent shell or falls back to $SHELL",
    )
    print_parser.set_defaults(func=_print)

    cleanup_parser = subparsers.add_parser(
        "cleanup-legacy",
        help="remove the rc block and data dir written by older versions",
    )
    cleanup_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="show what would be removed without modifying anything",
    )
    cleanup_parser.set_defaults(func=_cleanup_legacy)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if not getattr(args, "func", None):
        return _print(args)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
