"""Static shell completion for msmodeling commands.

The generated completion is pure shell code. Pressing Tab does not start Python
or import heavyweight runtime dependencies.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import site
import sys


MODULES = (
    "cli.inference.text_generate",
    "cli.inference.video_generate",
    "cli.inference.throughput_optimizer",
)

TOP_LEVEL_OPTIONS = (
    "--enable-tab-completion",
    "--disable-tab-completion",
    "--completion-shell",
    "--completion-rc-file",
    "--reload-shell",
    "--help",
)

COMMON_OPTIONS = (
    "--device",
    "--num-devices",
    "--reserved-memory-gb",
    "--log-level",
)

OPTIONS = {
    "text_generate": (
        *COMMON_OPTIONS,
        "--num-queries",
        "--query-length",
        "--context-length",
        "--decode",
        "--prefix-cache-hit-rate",
        "--num-mtp-tokens",
        "--disable-repetition",
        "--compile",
        "--compile-allow-graph-break",
        "--enable-sequence-parallel",
        "--quantize-linear-action",
        "--quantize-non-expert-linear-action",
        "--quantize-lmhead",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--graph-log-url",
        "--dump-input-shapes",
        "--dump-op-bound-results",
        "--chrome-trace",
        "--num-hidden-layers-override",
        "--tp-size",
        "--pp-size",
        "--dp-size",
        "--ep-size",
        "--o-proj-tp-size",
        "--o-proj-dp-size",
        "--mlp-tp-size",
        "--mlp-dp-size",
        "--lmhead-tp-size",
        "--lmhead-dp-size",
        "--moe-tp-size",
        "--moe-dp-size",
        "--word-embedding-tp",
        "--enable-redundant-experts",
        "--enable-shared-expert-tp",
        "--enable-external-shared-experts",
        "--host-external-shared-experts",
        "--vision-tp-size",
        "--image-batch-size",
        "--image-height",
        "--image-width",
        "--remote-source",
        "--performance-model",
        "--profiling-database",
        "--disable-profiling-interpolation",
        "--export-empirical-metrics",
        "--help",
    ),
    "video_generate": (
        "--device",
        "--batch-size",
        "--seq-len",
        "--chrome-trace",
        "--height",
        "--width",
        "--frame-num",
        "--sample-step",
        "--log-level",
        "--dtype",
        "--remote-source",
        "--quantize-linear-action",
        "--quantize-attention-action",
        "--use-cfg",
        "--world-size",
        "--ulysses-size",
        "--cfg-parallel",
        "--dit-cache",
        "--cache-step-range",
        "--cache-step-interval",
        "--cache-block-range",
        "--help",
    ),
    "throughput_optimizer": (
        *COMMON_OPTIONS,
        "--input-length",
        "--output-length",
        "--compile",
        "--compile-allow-graph-break",
        "--num-mtp-tokens",
        "--mtp-acceptance-rate",
        "--prefix-cache-hit-rate",
        "--quantize-linear-action",
        "--quantize-non-expert-linear-action",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--tp-sizes",
        "--ep-sizes",
        "--moe-dp-sizes",
        "--enable-shared-expert-tp",
        "--enable-sequence-parallel",
        "--enable-dispatch-ffn-combine",
        "--word-embedding-tp",
        "--performance-model",
        "--profiling-database",
        "--chrome-trace",
        "--ttft-limits",
        "--tpot-limits",
        "--max-batched-tokens",
        "--batch-range",
        "--serving-cost",
        "--disagg",
        "--jobs",
        "--max-search-combinations",
        "--concurrency-search-strategy",
        "--dump-original-results",
        "--image-batch-size",
        "--image-height",
        "--image-width",
        "--prefill-devices-per-instance",
        "--decode-devices-per-instance",
        "--enable-optimize-prefill-decode-ratio",
        "--help",
    ),
    "serving_cast_main": (
        "--instance_config_path",
        "--common_config_path",
        "--enable_profiling",
        "--profiling_output_path",
        "--output_json",
        "--help",
    ),
}

BLOCK_BEGIN = "# >>> msmodeling completion >>>"
BLOCK_END = "# <<< msmodeling completion <<<"
DATA_DIR = Path.home() / ".local" / "share" / "msmodeling"
BASH_COMPLETION_FILE = DATA_DIR / "completion.bash"


def _words(values: tuple[str, ...]) -> str:
    return " ".join(values)


def _ps_array(values: tuple[str, ...]) -> str:
    return "@(" + ", ".join(f"'{value}'" for value in values) + ")"


def render_bash_completion() -> str:
    """Return a self-contained bash completion script."""
    return f"""# Static completion for msmodeling.
# Generated by msmodeling --enable-tab-completion. Re-run after CLI option changes.

_msmodeling_complete()
{{
    local cmd cur prev target
    COMPREPLY=()
    cmd="${{COMP_WORDS[0]}}"
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev=""
    if [[ $COMP_CWORD -gt 0 ]]; then
        prev="${{COMP_WORDS[COMP_CWORD - 1]}}"
    fi

    if [[ "$cmd" == "msmodeling" ]]; then
        _msmodeling_complete_cli_command
        return 0
    fi

    if [[ $COMP_CWORD -gt 0 && "$prev" == "-m" ]]; then
        COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
        return 0
    fi

    case "$cur" in
        cli.inference.*)
            COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
            return 0
            ;;
    esac

    target="$(_msmodeling_completion_target)"
    if [[ -z "$target" || "$cur" != --* ]]; then
        return 0
    fi

    _msmodeling_complete_options "$target" "$cur"
}}

_msmodeling_complete_cli_command()
{{
    local cur first second target
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    first="${{COMP_WORDS[1]}}"
    second="${{COMP_WORDS[2]}}"

    if [[ $COMP_CWORD -eq 1 ]]; then
        if [[ "$cur" == --* ]]; then
            COMPREPLY=( $(compgen -W "{_words(TOP_LEVEL_OPTIONS)}" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "inference optix {_words(TOP_LEVEL_OPTIONS)}" -- "$cur") )
        fi
        return 0
    fi

    if [[ "$first" == "inference" && $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "text-generate throughput-optimizer model-adapter video-generate --help" -- "$cur") )
        return 0
    fi

    target="$(_msmodeling_cli_completion_target)"
    if [[ -z "$target" || "$cur" != --* ]]; then
        return 0
    fi
    _msmodeling_complete_options "$target" "$cur"
}}

_msmodeling_complete_options()
{{
    local target cur
    target="$1"
    cur="$2"

    case "$target" in
        text_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["text_generate"])}" -- "$cur") )
            ;;
        video_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["video_generate"])}" -- "$cur") )
            ;;
        throughput_optimizer)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["throughput_optimizer"])}" -- "$cur") )
            ;;
        serving_cast_main)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["serving_cast_main"])}" -- "$cur") )
            ;;
    esac
}}

_msmodeling_cli_completion_target()
{{
    case "${{COMP_WORDS[2]}}" in
        text-generate) echo text_generate; return 0 ;;
        video-generate) echo video_generate; return 0 ;;
        throughput-optimizer) echo throughput_optimizer; return 0 ;;
    esac
}}

_msmodeling_completion_target()
{{
    local i word next
    for ((i = 1; i < COMP_CWORD; i++)); do
        word="${{COMP_WORDS[i]}}"
        next="${{COMP_WORDS[i + 1]}}"

        if [[ "$word" == "-m" ]]; then
            case "$next" in
                cli.inference.text_generate) echo text_generate; return 0 ;;
                cli.inference.video_generate) echo video_generate; return 0 ;;
                cli.inference.throughput_optimizer) echo throughput_optimizer; return 0 ;;
                serving_cast.main) echo serving_cast_main; return 0 ;;
            esac
        fi

        case "$word" in
            */cli/inference/text_generate.py|cli/inference/text_generate.py|text_generate.py)
                echo text_generate; return 0 ;;
            */cli/inference/video_generate.py|cli/inference/video_generate.py|video_generate.py)
                echo video_generate; return 0 ;;
            */cli/inference/throughput_optimizer.py|cli/inference/throughput_optimizer.py|throughput_optimizer.py)
                echo throughput_optimizer; return 0 ;;
            */serving_cast/main.py|serving_cast/main.py)
                echo serving_cast_main; return 0 ;;
        esac
    done
}}

complete -o default -F _msmodeling_complete python python3 msmodeling
"""


def render_zsh_completion() -> str:
    """Return a self-contained zsh completion script via bashcompinit."""
    return (
        "# Static completion for msmodeling in zsh via bashcompinit.\n"
        "autoload -Uz +X compinit && compinit -u 2>/dev/null\n"
        "autoload -Uz +X bashcompinit && bashcompinit\n"
        + render_bash_completion()
    )


def render_powershell_completion() -> str:
    """Return a self-contained PowerShell completion script."""
    return f"""# Static completion for msmodeling.
# Generated by msmodeling --enable-tab-completion. Re-run after CLI option changes.

$script:MsmodelingModules = {_ps_array(MODULES)}
$script:MsmodelingOptions = @{{
    'text_generate' = {_ps_array(OPTIONS["text_generate"])}
    'video_generate' = {_ps_array(OPTIONS["video_generate"])}
    'throughput_optimizer' = {_ps_array(OPTIONS["throughput_optimizer"])}
    'serving_cast_main' = {_ps_array(OPTIONS["serving_cast_main"])}
}}

function Get-MsmodelingCompletionTarget {{
    param([string[]] $Words)

    for ($i = 1; $i -lt $Words.Count; $i++) {{
        $word = $Words[$i]
        $next = if ($i + 1 -lt $Words.Count) {{ $Words[$i + 1] }} else {{ "" }}

        if ($word -eq "-m") {{
            switch ($next) {{
                "cli.inference.text_generate" {{ return "text_generate" }}
                "cli.inference.video_generate" {{ return "video_generate" }}
                "cli.inference.throughput_optimizer" {{ return "throughput_optimizer" }}
                "serving_cast.main" {{ return "serving_cast_main" }}
            }}
        }}

        switch -Wildcard ($word) {{
            "*/cli/inference/text_generate.py" {{ return "text_generate" }}
            "*\\cli\\inference\\text_generate.py" {{ return "text_generate" }}
            "cli/inference/text_generate.py" {{ return "text_generate" }}
            "cli\\inference\\text_generate.py" {{ return "text_generate" }}
            "text_generate.py" {{ return "text_generate" }}
            "*/cli/inference/video_generate.py" {{ return "video_generate" }}
            "*\\cli\\inference\\video_generate.py" {{ return "video_generate" }}
            "cli/inference/video_generate.py" {{ return "video_generate" }}
            "cli\\inference\\video_generate.py" {{ return "video_generate" }}
            "video_generate.py" {{ return "video_generate" }}
            "*/cli/inference/throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "*\\cli\\inference\\throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "cli/inference/throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "cli\\inference\\throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "throughput_optimizer.py" {{ return "throughput_optimizer" }}
            "*/serving_cast/main.py" {{ return "serving_cast_main" }}
            "*\\serving_cast\\main.py" {{ return "serving_cast_main" }}
            "serving_cast/main.py" {{ return "serving_cast_main" }}
            "serving_cast\\main.py" {{ return "serving_cast_main" }}
        }}
    }}
}}

Register-ArgumentCompleter -Native -CommandName @("python", "python3") -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = @($commandAst.CommandElements | ForEach-Object {{ $_.ToString() }})
    if ($words.Count -gt 1 -and $words[$words.Count - 2] -eq "-m") {{
        $script:MsmodelingModules |
            Where-Object {{ $_ -like "$wordToComplete*" }} |
            ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_) }}
        return
    }}

    if ($wordToComplete -like "cli.inference.*") {{
        $script:MsmodelingModules |
            Where-Object {{ $_ -like "$wordToComplete*" }} |
            ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_) }}
        return
    }}

    $target = Get-MsmodelingCompletionTarget -Words $words
    if (-not $target -or -not $wordToComplete.StartsWith("--")) {{
        return
    }}

    $script:MsmodelingOptions[$target] |
        Where-Object {{ $_ -like "$wordToComplete*" }} |
        ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterName", $_) }}
}}
"""


def _detect_shell() -> str:
    try:
        comm = Path(f"/proc/{os.getppid()}/comm").read_text(encoding="utf-8").strip()
        if comm in {"bash", "zsh"}:
            return comm
        if comm in {"pwsh", "powershell"}:
            return "powershell"
    except OSError:
        pass

    shell_name = Path(os.environ.get("SHELL", "")).name.lower()
    if shell_name in {"bash", "zsh"}:
        return shell_name
    if os.environ.get("PSModulePath"):
        return "powershell"
    return "bash"


def _resolve_shell(value: str) -> str:
    if value in {"bash", "zsh", "powershell"}:
        return value
    return _detect_shell()


def _default_prefix(user: bool) -> Path:
    if user:
        return Path(site.getuserbase())
    return Path(sys.prefix)


def _bash_target(prefix: Path) -> Path:
    return prefix / "share" / "bash-completion" / "completions" / "msmodeling-python"


def _zsh_target(prefix: Path) -> Path:
    return prefix / "share" / "zsh" / "site-functions" / "_msmodeling-python"


def _powershell_target(prefix: Path) -> Path:
    return prefix / "share" / "powershell" / "Completions" / "msmodeling.ps1"


def _write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def _completion_for_shell(shell: str) -> str:
    if shell == "zsh":
        return render_zsh_completion()
    if shell == "powershell":
        return render_powershell_completion()
    return render_bash_completion()


def _rc_file_for_shell(shell: str) -> Path:
    if shell == "zsh":
        return Path.home() / ".zshrc"
    if shell == "powershell":
        raise ValueError("PowerShell rc updates are not supported by --enable-tab-completion yet.")
    return Path.home() / ".bashrc"


def _managed_block(completion_path: Path) -> str:
    return (
        f"{BLOCK_BEGIN}\n"
        f'if [ -r "{completion_path}" ]; then\n'
        f'    . "{completion_path}"\n'
        "fi\n"
        f"{BLOCK_END}\n"
    )


def _replace_managed_block(contents: str, block: str) -> str:
    lines = contents.splitlines(keepends=True)
    result: list[str] = []
    in_block = False
    replaced = False

    for line in lines:
        stripped = line.strip()
        if stripped == BLOCK_BEGIN:
            if not replaced:
                if result and result[-1].strip():
                    result.append("\n")
                result.append(block)
                replaced = True
            in_block = True
            continue
        if stripped == BLOCK_END:
            in_block = False
            continue
        if not in_block:
            result.append(line)

    if not replaced:
        if result and result[-1].strip():
            result.append("\n")
        result.append(block)

    return "".join(result)


def _remove_managed_block(contents: str) -> str:
    lines = contents.splitlines(keepends=True)
    result: list[str] = []
    in_block = False
    for line in lines:
        stripped = line.strip()
        if stripped == BLOCK_BEGIN:
            in_block = True
            continue
        if stripped == BLOCK_END:
            in_block = False
            continue
        if not in_block:
            result.append(line)
    return "".join(result)


def enable_tab_completion(
    shell: str = "auto",
    rc_file: str | Path | None = None,
    completion_file: str | Path | None = None,
    reload_shell: bool = False,
) -> int:
    resolved_shell = _resolve_shell(shell)
    if resolved_shell != "bash":
        print("Only bash startup-file enablement is currently supported.", file=sys.stderr)
        print("For zsh use: . <(msmodeling-tab print --shell zsh)", file=sys.stderr)
        return 1

    completion_path = Path(completion_file) if completion_file is not None else BASH_COMPLETION_FILE
    _write(completion_path, render_bash_completion())

    target_rc = Path(rc_file) if rc_file is not None else _rc_file_for_shell(resolved_shell)
    original = target_rc.read_text(encoding="utf-8") if target_rc.exists() else ""
    target_rc.write_text(_replace_managed_block(original, _managed_block(completion_path)), encoding="utf-8")

    print(f"Enabled msmodeling tab completion in {target_rc}")
    print(f"Wrote static completion script to {completion_path}")
    print("Open a new bash terminal to use it, or run: exec bash")

    if reload_shell:
        os.execvp("bash", ["bash"])
    return 0


def disable_tab_completion(shell: str = "auto", rc_file: str | Path | None = None) -> int:
    resolved_shell = _resolve_shell(shell)
    if resolved_shell != "bash":
        print("Only bash startup-file disablement is currently supported.", file=sys.stderr)
        return 1

    target_rc = Path(rc_file) if rc_file is not None else _rc_file_for_shell(resolved_shell)
    if not target_rc.exists():
        print(f"No shell startup file found at {target_rc}")
        return 0

    target_rc.write_text(_remove_managed_block(target_rc.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"Disabled msmodeling tab completion in {target_rc}")
    return 0


def install_completion_files(prefix: str | None = None, user: bool = False) -> int:
    target_prefix = Path(prefix) if prefix else _default_prefix(user)
    bash_path = _bash_target(target_prefix)
    zsh_path = _zsh_target(target_prefix)
    powershell_path = _powershell_target(target_prefix)
    _write(bash_path, render_bash_completion())
    _write(zsh_path, render_zsh_completion())
    _write(powershell_path, render_powershell_completion())
    print(f"Wrote bash completion: {bash_path}")
    print(f"Wrote zsh  completion: {zsh_path}")
    print(f"Wrote PowerShell completion: {powershell_path}")
    return 0


def print_completion(shell: str = "auto") -> int:
    sys.stdout.write(_completion_for_shell(_resolve_shell(shell)))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Emit, install, enable, or disable static shell completion for msmodeling.",
    )
    parser.add_argument(
        "--shell",
        choices=("auto", "bash", "zsh", "powershell"),
        default="auto",
        help="target shell for the print command",
    )
    subparsers = parser.add_subparsers(dest="command")

    install_parser = subparsers.add_parser("install", help="write completion files under <prefix>/share")
    install_parser.add_argument("--prefix", default=None)
    install_parser.add_argument("--user", action="store_true")

    print_parser = subparsers.add_parser("print", help="print completion script")
    print_parser.add_argument(
        "--shell",
        dest="print_shell",
        choices=("auto", "bash", "zsh", "powershell"),
        default=None,
        help="target shell; may also be passed before the subcommand",
    )
    subparsers.add_parser("enable", help="enable bash completion from ~/.bashrc")
    subparsers.add_parser("disable", help="disable bash completion from ~/.bashrc")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if args.command == "install":
        return install_completion_files(args.prefix, args.user)
    if args.command == "enable":
        return enable_tab_completion(args.shell)
    if args.command == "disable":
        return disable_tab_completion(args.shell)
    return print_completion(getattr(args, "print_shell", None) or args.shell)


if __name__ == "__main__":
    sys.exit(main())
