"""Install static shell completion for the msmodeling CLI entry points."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys


MODULES = (
    "cli.inference.text_generate",
    "cli.inference.video_generate",
    "cli.inference.throughput_optimizer",
)

COMMON_OPTIONS = (
    "--device",
    "--num-devices",
    "--reserved-memory-gb",
    "--log-level",
)

OPTIONS = {
    "text_generate": (
        *COMMON_OPTIONS,
        "--num-queries",
        "--query-length",
        "--context-length",
        "--decode",
        "--prefix-cache-hit-rate",
        "--num-mtp-tokens",
        "--disable-repetition",
        "--compile",
        "--compile-allow-graph-break",
        "--quantize-linear-action",
        "--quantize-lmhead",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--graph-log-url",
        "--dump-input-shapes",
        "--chrome-trace",
        "--num-hidden-layers-override",
        "--tp-size",
        "--dp-size",
        "--ep-size",
        "--o-proj-tp-size",
        "--o-proj-dp-size",
        "--mlp-tp-size",
        "--mlp-dp-size",
        "--lmhead-tp-size",
        "--lmhead-dp-size",
        "--moe-tp-size",
        "--moe-dp-size",
        "--word-embedding-tp",
        "--enable-redundant-experts",
        "--enable-external-shared-experts",
        "--host-external-shared-experts",
        "--image-batch-size",
        "--image-height",
        "--image-width",
        "--remote-source",
        "--performance-model",
        "--profiling-database",
        "--help",
    ),
    "video_generate": (
        "--device",
        "--batch-size",
        "--seq-len",
        "--chrome-trace",
        "--height",
        "--width",
        "--frame-num",
        "--sample-step",
        "--log-level",
        "--dtype",
        "--quantize-linear-action",
        "--use-cfg",
        "--world-size",
        "--ulysses-size",
        "--cfg-parallel",
        "--dit-cache",
        "--cache-step-range",
        "--cache-step-interval",
        "--cache-block-range",
        "--help",
    ),
    "throughput_optimizer": (
        *COMMON_OPTIONS,
        "--input-length",
        "--output-length",
        "--compile",
        "--compile-allow-graph-break",
        "--num-mtp-tokens",
        "--mtp-acceptance-rate",
        "--prefix-cache-hit-rate",
        "--quantize-linear-action",
        "--mxfp4-group-size",
        "--quantize-attention-action",
        "--tp-sizes",
        "--ep-sizes",
        "--moe-dp-sizes",
        "--ttft-limits",
        "--tpot-limits",
        "--max-prefill-tokens",
        "--batch-range",
        "--serving-cost",
        "--disagg",
        "--jobs",
        "--dump-original-results",
        "--image-height",
        "--image-width",
        "--prefill-devices-per-instance",
        "--decode-devices-per-instance",
        "--enable-optimize-prefill-decode-ratio",
        "--help",
    ),
    "serving_cast_main": (
        "--instance_config_path",
        "--common_config_path",
        "--enable_profiling",
        "--profiling_output_path",
        "--help",
    ),
}

INSTALL_DIR = Path.home() / ".local" / "share" / "msmodeling" / "completion"
BASH_FILE = INSTALL_DIR / "msmodeling-completion.bash"
ZSH_FILE = INSTALL_DIR / "msmodeling-completion.zsh"


def _words(values: tuple[str, ...]) -> str:
    return " ".join(values)


def render_bash_completion() -> str:
    return f"""# Static completion for msmodeling.
# Generated by msmodeling-completion. Re-run after CLI option changes.

_msmodeling_complete()
{{
    local cur target
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"

    if [[ $COMP_CWORD -gt 0 && ${{COMP_WORDS[COMP_CWORD - 1]}} == "-m" ]]; then
        COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
        return 0
    fi

    case "$cur" in
        cli.inference.*)
            COMPREPLY=( $(compgen -W "{_words(MODULES)}" -- "$cur") )
            return 0
            ;;
    esac

    target="$(_msmodeling_completion_target)"
    if [[ -z "$target" || "$cur" != --* ]]; then
        return 0
    fi

    case "$target" in
        text_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["text_generate"])}" -- "$cur") )
            ;;
        video_generate)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["video_generate"])}" -- "$cur") )
            ;;
        throughput_optimizer)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["throughput_optimizer"])}" -- "$cur") )
            ;;
        serving_cast_main)
            COMPREPLY=( $(compgen -W "{_words(OPTIONS["serving_cast_main"])}" -- "$cur") )
            ;;
    esac
}}

_msmodeling_completion_target()
{{
    local i word next
    for ((i = 1; i < COMP_CWORD; i++)); do
        word="${{COMP_WORDS[i]}}"
        next="${{COMP_WORDS[i + 1]}}"

        if [[ "$word" == "-m" ]]; then
            case "$next" in
                cli.inference.text_generate) echo text_generate; return 0 ;;
                cli.inference.video_generate) echo video_generate; return 0 ;;
                cli.inference.throughput_optimizer) echo throughput_optimizer; return 0 ;;
                serving_cast.main) echo serving_cast_main; return 0 ;;
            esac
        fi

        case "$word" in
            */cli/inference/text_generate.py|cli/inference/text_generate.py|text_generate.py)
                echo text_generate; return 0 ;;
            */cli/inference/video_generate.py|cli/inference/video_generate.py|video_generate.py)
                echo video_generate; return 0 ;;
            */cli/inference/throughput_optimizer.py|cli/inference/throughput_optimizer.py|throughput_optimizer.py)
                echo throughput_optimizer; return 0 ;;
            */serving_cast/main.py|serving_cast/main.py)
                echo serving_cast_main; return 0 ;;
        esac
    done
}}

complete -o default -F _msmodeling_complete python python3
"""


def render_zsh_completion() -> str:
    return """# Static completion for msmodeling in zsh via bashcompinit.
autoload -Uz bashcompinit
bashcompinit
source "${0:A:h}/msmodeling-completion.bash"
"""


def _rc_file(shell: str) -> Path:
    if shell == "zsh":
        return Path.home() / ".zshrc"
    return Path.home() / ".bashrc"


def _rc_block(shell: str) -> str:
    script = ZSH_FILE if shell == "zsh" else BASH_FILE
    return (
        "# >>> msmodeling completion >>>\n"
        f"source {script}\n"
        "# <<< msmodeling completion <<<\n"
    )


def _detect_shell() -> str:
    shell = Path(os.environ.get("SHELL", "")).name
    if shell in {"bash", "zsh"}:
        return shell
    return "bash"


def _write_scripts() -> None:
    INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    BASH_FILE.write_text(render_bash_completion(), encoding="utf-8")
    ZSH_FILE.write_text(render_zsh_completion(), encoding="utf-8")


def _install(args: argparse.Namespace) -> int:
    shell = args.shell or _detect_shell()
    _write_scripts()
    if not args.no_rc:
        rc_file = _rc_file(shell)
        block = _rc_block(shell)
        current = rc_file.read_text(encoding="utf-8") if rc_file.exists() else ""
        if "# >>> msmodeling completion >>>" not in current:
            with rc_file.open("a", encoding="utf-8") as handle:
                if current and not current.endswith("\n"):
                    handle.write("\n")
                handle.write(block)
    print(f"Installed msmodeling {shell} completion.")
    print("Open a new shell or run:")
    print(f"  source {ZSH_FILE if shell == 'zsh' else BASH_FILE}")
    return 0


def _print(args: argparse.Namespace) -> int:
    if args.shell == "zsh":
        sys.stdout.write(render_zsh_completion())
    else:
        sys.stdout.write(render_bash_completion())
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    install_parser = subparsers.add_parser(
        "install",
        help="install shell completion and update the current user's shell rc file",
    )
    install_parser.add_argument("--shell", choices=("bash", "zsh"), default=None)
    install_parser.add_argument(
        "--no-rc",
        action="store_true",
        help="write completion files without editing ~/.bashrc or ~/.zshrc",
    )
    install_parser.set_defaults(func=_install)

    print_parser = subparsers.add_parser("print", help="print completion script")
    print_parser.add_argument("--shell", choices=("bash", "zsh"), default="bash")
    print_parser.set_defaults(func=_print)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
