name: UT Job

on:
  workflow_call:
    inputs:
      REMOTE_URL:
        required: false
        type: string
        default: ${{ atomgit.repositoryurl }}
      pr_id:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.number }}
      IMAGE_FLAG:
        required: true
        type: string
      TARGET_BRANCH:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.base.ref }}
      runs_on_arch:
        required: true
        type: string
    secrets:
      GITCODE_TOKEN:
        required: true

jobs:
  JOB_UT:
    name: JOB_UT
    select: selected_by_default
    runs-on: [ dedicate-hosted, "${{ inputs.runs_on_arch }}", large ]
    container:
      image: swr.cn-north-4.myhuaweicloud.com/mindstudio-image/${{ inputs.IMAGE_FLAG }}
      options: --user root
    steps:
      - name: setup git credentials
        env:
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        run: |
          set -e
          touch /root/.git-credentials
          echo "https://AtlasAccount:${GITCODE_TOKEN}@gitcode.com" >> /root/.git-credentials
          git config --global credential.helper store
          git config --global credential.helper 'store --file /root/.git-credentials'
          chmod 600 /root/.git-credentials
          ls -l /root/.git-credentials
      - name: install dependencies
        run: |
          set -e
          apt install lcov -y
          apt install libboost-all-dev -y
          ln -sf /usr/local/python3.10/bin/python3.10 /usr/bin/python3
          ln -sf /usr/local/python3.10/bin/pip3.10 /usr/bin/pip3
          ln -sf /usr/local/python3.10/bin/pip3.10 /usr/bin/pip
          python3 --version
          pip3 install lcov_cobertura
          pip3 install diff-cover
          pip3 install coverage pytest
      - name: clone repo and merge PR
        run: |
          set -ex
          git clone -b ${{ inputs.TARGET_BRANCH }} ${{ inputs.REMOTE_URL }} CODE
          cd CODE
          git config --global user.email "AtlasAccount@noreply.gitcode.com"
          git config --global user.name "AtlasAccount"
          git fetch origin
          git fetch origin refs/merge-requests/${{ inputs.pr_id }}/head:new_${{ inputs.pr_id }}
          git checkout new_${{ inputs.pr_id }}
          git merge origin/${{ inputs.TARGET_BRANCH }}
          git diff-tree -r --name-only --no-commit-id origin/${{ inputs.TARGET_BRANCH }} HEAD > ../modify_files.txt
          cat ../modify_files.txt
      - name: execute test
        run: |
          set -ex
          export PATH=/usr/local/python3.10/bin:"${PATH}"
          cd ${ATOMGIT_WORKSPACE}/CODE
          bash scripts/download_thirdparty.sh ut
          bash scripts/execute_cpp_test_case.sh
          bash scripts/execute_py_test_case.sh
