import subprocess
from typing import Optional, Tuple
from loguru import logger
from optix.config.config import get_settings, OptimizerConfigField
from optix.config.constant import ProcessState, Stage
from optix.optimizer.interfaces.simulator import SimulatorInterface
from optix.optimizer.utils import close_file_fp
from multihost_inference_optimization.settings import MultiHostCommandConfig
from multihost_inference_optimization.vllm_worker_manager import VLLMWorkerManager
from multihost_inference_optimization.nic_resolver import resolve_nic_names
import json
import shutil
import shlex
import re
import tempfile
from pathlib import Path
import os
import sys
import requests

class MultihostCommand:
    """Build the vllm command template (with placeholders); this exists only to satisfy
    the base class SimulatorInterface's requirement for a self.command attribute. In the
    multi-node case, startup actually goes through the shell scripts generated by
    _build_shell_scripts, and this command list is never executed directly."""
    def __init__(self, command_config: MultiHostCommandConfig):
        self.process = shutil.which("vllm")
        if self.process is None:
           raise ValueError("Error: The 'vllm' executable was not found in the system PATH.")
        self.command_config = command_config
 
    @property
    def command(self):
        origin_cmd = [self.process, "serve",
                self.command_config.model,
                "--served-model-name", self.command_config.served_model_name,
                "--host", self.command_config.host,
                "--port", self.command_config.port,
                "--max-num-batched-tokens", "$MAX_NUM_BATCHED_TOKENS",
                "--max-num-seqs", "$MAX_NUM_SEQS"]

        if self.command_config.others:
            origin_cmd.extend(shlex.split(self.command_config.others))        
        return origin_cmd

class MultiHostSimulator(SimulatorInterface):
    """Simulator (launcher) for the multi-node vLLM distributed inference service"""
    def __init__(self, config = None, *args, **kwargs):
        settings = get_settings()
        # This simulator depends on settings.vllm (a base Settings field) rather than on
        # any particular plugin's custom Settings subclass. When several plugins that
        # provide Settings are installed at once, register_settings keeps only the last
        # one registered and settings.name is no longer reliable, so we validate only the
        # vllm configuration we actually need.
        self.config = getattr(settings, "vllm", None)
        if self.config is None:
            raise ValueError(
                "Invalid settings: missing 'vllm' configuration required by "
                "MultiHostSimulator.")
        super().__init__(*args, process_name=self.config.process_name, **kwargs)

        self.command = MultihostCommand(self.config.command).command
        self.remote_executor = VLLMWorkerManager()
        # Per-node NIC names {host: nic_name}: detected once before optimization starts
        # and reused in later cycles
        self._nic_names: Optional[dict] = None

    @property
    def base_url(self) -> str:
        """
        Get the service's base url property
        Returns:

        """
        return f"http://127.0.0.1:{self.config.command.port}/health"


    def test_cluster_simple(self, served_model_name: str) -> bool:
        """Send one real inference request to verify the whole multi-node cluster is ready and working together."""
        url = f"http://127.0.0.1:{self.config.command.port}/v1/completions"
        payload = {
            "model": served_model_name,
            "prompt": "Hello",
            "max_tokens": 10
        }
        try:
            response = requests.post(url, json=payload, timeout=30)
            if response.status_code == 200:
                return True
            else:
                logger.info(f"Cluster not ready: HTTP {response.status_code}")
                return False
        except Exception as e:
            logger.error(f"Connection failed {e}")
            return False

    
    def health(self) -> ProcessState:
        """
        Get the current state of the service.
        The current implementation uses the basic vllm url.
        Returns: None

        When vllm serve on the master node has started but the worker node processes have
        not, the master's /health endpoint usually still responds normally.
        The most reliable check: once the workers have finished starting, send a real
        inference request; if it returns normally, the whole distributed system is fully
        ready. This works because in a multi-node data parallel architecture, handling a
        single request requires all nodes to work together.

        """
        last_process_stage = self.process_stage
        process_res = super().health()
        if process_res.stage == Stage.error:
            return process_res
        try:
            res = requests.get(self.base_url, timeout=10)
        except requests.exceptions.RequestException as e:
            if last_process_stage.stage == Stage.start:
                return ProcessState(stage=Stage.start, info=str(e))
            return ProcessState(stage=Stage.error, info=str(e))
        else:
            if res.status_code == 200:
                if self.test_cluster_simple(self.config.command.served_model_name):
                    return ProcessState(stage=Stage.running)
                else:
                    # The master is healthy but the cluster is not yet working together,
                    # so keep waiting
                    return ProcessState(stage=Stage.start, info="Health OK but cluster not fully ready")
            # 503 means the service process has started but is not ready yet (e.g. the
            # model is still loading), which should count as "starting" and keep waiting
            if res.status_code == 503:
                return ProcessState(stage=Stage.start, info=f"return code {res.status_code}. text {res.text}")
            return ProcessState(stage=Stage.error, info=f"return code {res.status_code}. text {res.text}")
    

    def update_command(self):
        self.command = MultihostCommand(self.config.command).command

    # Mapping from tuning variable name to vllm CLI flag (only parameters vllm recognizes).
    # Matched variables are appended to the vllm command line automatically, so the user
    # does not have to write them in `others` by hand.
    _ENV_TO_CLI_FLAG = {
        "MAX_NUM_BATCHED_TOKENS": "--max-num-batched-tokens",
        "MAX_NUM_SEQS": "--max-num-seqs",
    }

    def _collect_env_vars(self, run_params: Optional[Tuple[OptimizerConfigField]] = None) -> dict:
        """Collect the tuning variables with config_position="env" from run_params."""
        env_vars: dict = {}
        if run_params:
            for k in run_params:
                if k.config_position == "env" and k.value is not None:
                    env_vars[k.name.upper().strip()] = str(k.value)
        return env_vars

    def _resolve_vllm_params(self, env_vars: dict) -> str:
        """Assemble served_model_name, the CLI-mapped variables, and others into a vllm parameter string.

        - variables in _ENV_TO_CLI_FLAG are mapped to CLI flags automatically
        - $VAR_NAME placeholders in others are replaced with actual values
        """
        cmd_config = self.config.command
        parts = []
        if cmd_config.served_model_name:
            parts.extend(["--served-model-name", cmd_config.served_model_name])

        # Automatically turn the tuning variables in the mapping table into CLI arguments
        for var_name, cli_flag in self._ENV_TO_CLI_FLAG.items():
            if var_name in env_vars:
                parts.extend([cli_flag, env_vars[var_name]])

        if cmd_config.others:
            # Replace the $VAR_NAME placeholders in others with the actual tuning variable
            # values. A single regex pass with identifier boundaries avoids the prefix
            # overlap problem of repeated str.replace calls (e.g. $DP being a prefix of
            # $DP_LOCAL would clobber it); undefined variables are left as-is.
            def _sub_var(m):
                name = m.group(1)
                return env_vars.get(name, m.group(0))
            others_resolved = re.sub(
                r'\$([A-Za-z_][A-Za-z0-9_]*)', _sub_var, cmd_config.others
            )
            parts.append(others_resolved)
        return " ".join(parts)

    def _resolve_nic_names(self) -> dict:
        """Detect the NIC name matching each node's IP, caching the result for reuse.

        A node may not have iproute2 installed (no `ip` command), so NIC names are not
        detected on the spot inside the startup scripts. Instead they are detected here
        using each node's own Python (detect_nic.py) and rendered into the generated
        scripts. Detection runs only during the first optimization cycle: the NIC topology
        does not change during a run, so there is no need to pay the SSH cost every cycle.

        Nodes that explicitly configure nic_name in config.toml are not probed; the
        configured value is used as-is.
        """
        if self._nic_names is None:
            self._nic_names = resolve_nic_names(self.remote_executor.config)
            logger.info(f"Resolved nic_name for all nodes: {self._nic_names}")
        return self._nic_names

    def _get_output_dir(self) -> Path:
        """Determine the script output directory: persist it under the backup path when one exists, otherwise use a temporary directory."""
        bak_path = getattr(self, "bak_path", None)
        if bak_path:
            output_dir = Path(bak_path) / "Reproduce"
        else:
            output_dir = Path(tempfile.mkdtemp(prefix="ms_multihost_scripts_"))
        output_dir.mkdir(parents=True, exist_ok=True, mode=0o750)
        return output_dir

    def _build_shell_scripts(self, run_params: Optional[Tuple[OptimizerConfigField]] = None):
        """Invoke build_shell_scripts.py to generate the startup script for each node.

        Flow: determine the output directory → collect tuning variables → assemble the
        vllm parameters → invoke the builder subprocess.
        """
        plugin_dir = Path(__file__).resolve().parent
        builder = plugin_dir / "build_shell_scripts.py"
        template_file = plugin_dir / "template.sh"
        config_file = Path(os.environ.get("CLUSTER_CONFIG_PATH")) if os.environ.get("CLUSTER_CONFIG_PATH") else plugin_dir / "config.toml"

        output_dir = self._get_output_dir()
        self.remote_executor.set_build_scripts_dir(output_dir)

        # NIC names are detected here first (on the first cycle) and passed through to the
        # builder, so the builder subprocess does not re-run the SSH probe on every
        # optimization cycle.        
        nic_names_json = json.dumps(self._resolve_nic_names(), ensure_ascii=False)
        env_vars = self._collect_env_vars(run_params)
        vllm_params = self._resolve_vllm_params(env_vars)
        # Encode env_vars as JSON so values containing commas / spaces / quotes (such as
        # the JSON string for --compilation-config) are not truncated while being passed
        # and parsed.
        env_vars_json = json.dumps(env_vars, ensure_ascii=False) if env_vars else ""

        cmd = [
            sys.executable, str(builder),
            "--model-name", str(self.config.command.model),
            "--port", str(self.config.command.port),
            "--vllm-params", vllm_params,
            "--output-dir", str(output_dir),
            "--template-file", str(template_file),
            "--config-file", str(config_file),
            "--nic-names", nic_names_json,
        ]
        if env_vars_json:
            cmd.extend(["--env-vars", env_vars_json])
        logger.info(f"Generating shell scripts: {' '.join(shlex.quote(c) for c in cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(
                f"Failed to build shell scripts (return code {result.returncode}). "
                f"stdout: {result.stdout}. stderr: {result.stderr}")
        logger.info(f"Build shell scripts done:\n{result.stdout.strip()}")

    def before_run(self, run_params: Optional[Tuple[OptimizerConfigField]] = None):
        # Create the log file for the local node process (read by health/get_last_log).
        # Note: this class does not reuse the base class before_run's command parameter
        # substitution logic (multi-node parameters are injected through the generated
        # scripts) and only needs the log file, so it is created separately here.
        self.run_log_fp, self.run_log = tempfile.mkstemp(prefix="ms_serviceparam_optimizer_")
        self.run_log_offset = 0

        try:
            # Generate the per-node startup scripts (from config.toml and template.sh),
            # persisted per cycle
            logger.debug("build shell scripts")
            self._build_shell_scripts(run_params)

            logger.debug("uploading scripts to worker servers...")
            self.remote_executor.upload_all_scripts()

            logger.debug("checking and cleaning residual processes...")
            self.remote_executor.cleanup_all_workers()
        except Exception:
            close_file_fp(self.run_log_fp)
            self.run_log_fp = None
            raise

    def _launch_node_local(self):
        """Launch start_node.sh in the background on the local machine (the node that shares a machine with the optimizer).

        The node serves the API to the outside and health() probes it via 127.0.0.1:port,
        so it is launched non-blockingly with subprocess.Popen and the process is handed to
        the base class's self.process, which makes the self.process.poll() logic in
        health()/stop() work.
        """
        node_script = Path(self.remote_executor.get_build_scripts_dir()) / "start_node.sh"
        if not node_script.is_file():
            raise RuntimeError(f"node startup script not found: {node_script}")

        # Reuse the base class's log file mechanism: before_run already created self.run_log
        log_path = self.run_log
        cmd = ["bash", "-l", str(node_script)]
        logger.info(f"[start_node] launching locally: {' '.join(cmd)}, log={log_path}")

        # Close the fd left behind by mkstemp in before_run and hand the subprocess an
        # append-mode handle instead, to avoid leaking the fd
        if self.run_log_fp is not None:
            try:
                os.close(self.run_log_fp)
            except OSError:
                pass
            self.run_log_fp = None

        log_fp = open(log_path, "a", encoding="utf-8") if log_path else subprocess.DEVNULL
        try:
            self.process = subprocess.Popen(
                cmd, stdout=log_fp, stderr=subprocess.STDOUT,
                cwd=str(node_script.parent),
            )
        finally:            
            if log_fp is not subprocess.DEVNULL:
                log_fp.close()
        self.process_stage = ProcessState(stage=Stage.start)
        logger.info(f"[start_node] started locally, pid={self.process.pid}")

    def run(self, run_params: Optional[Tuple[OptimizerConfigField]] = None, **kwargs):
        """Launch the whole DP cluster non-blockingly and return immediately; health() decides when the cluster is ready.

        The scheduler only calls run() (it never calls before_run separately), so
        self.before_run must be invoked explicitly here to generate and upload the scripts
        and clean up leftovers.

        Startup order: start the local node first (the DP coordinator that
        data-parallel-address points at), then launch each worker in the background over
        SSH. Both are non-blocking, so the processes run concurrently.
        """
        # Clean up leftover vllm processes on the local node
        if self.process_name:
            try:
                self.kill_residual_process(self.process_name)
            except Exception as e:
                logger.error(f"Failed to kill residual process. {e}")

        # Generate the scripts, upload them to the workers, clean up worker leftovers
        # (and create self.run_log)
        self.before_run(run_params)

        try:
            # 1. Launch the node (master) locally, non-blocking
            self._launch_node_local()
            # 2. Launch all worker nodes in the background over SSH, non-blocking
            self.remote_executor.start_workers(run_params)
        except Exception as e:
            logger.error(f"Failed to start MultiHost vLLM cluster: {e}")
            self.stop(del_log=False)
            raise

    def stop(self, del_log: bool = True):
        # Stop the local node process (the base class kills self.process specifically)
        super().stop(del_log)
        # Clean up leftover processes on all worker nodes
        self.remote_executor.cleanup_all_workers()
